import { StyleSheet } from 'react-native';
import { THEME } from '../constants/theme';

export const guidesStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: THEME.colors.background,
        paddingTop: THEME.spacing.paddingPageTop,
        paddingHorizontal: THEME.spacing.paddingStandard,
    },
    headerRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    headerTitle: {
        fontSize: 22,
        fontWeight: '800',
        color: THEME.colors.primary,
    },
    mainDivider: {
        height: THEME.borderWidth.default,
        backgroundColor: THEME.colors.primary,
        width: '100%',
        marginBottom: 24,
    },
    infoBox: {
        backgroundColor: THEME.colors.container,
        borderTopWidth: THEME.borderWidth.default,
        borderLeftWidth: THEME.borderWidth.default,
        borderRightWidth: 0,
        borderBottomWidth: 0,
        borderColor: THEME.colors.border,
        borderRadius: THEME.borderRadius.default,
        padding: THEME.spacing.paddingArticleContainer,
        marginBottom: 24,
    },
    infoText: {
        color: THEME.colors.white,
        fontSize: 16,
        lineHeight: 24,
    },
    tagsContainer: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 24,
        flexWrap: 'wrap',
    },
    tag: {
        backgroundColor: THEME.colors.tag,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: THEME.borderRadius.rounded,
        borderColor: THEME.colors.border,
    },
    tagText: {
        color: THEME.colors.black,
        fontSize: 11,
        fontWeight: '800',
    },
    card: {
        flexDirection: 'row',
        backgroundColor: THEME.colors.container,
        borderTopWidth: THEME.borderWidth.default,
        borderLeftWidth: THEME.borderWidth.default,
        borderRightWidth: 0,
        borderBottomWidth: 0,
        borderColor: THEME.colors.border,
        borderRadius: THEME.borderRadius.default,
        marginBottom: 16,
        overflow: 'hidden',
    },
    cardImage: {
        width: 120,
        height: '100%',
        minHeight: 100,
    },
    cardContent: {
        flex: 1,
        padding: THEME.spacing.paddingArticleContainer,
        justifyContent: 'center',
    },
    cardTitle: {
        color: THEME.colors.white,
        fontSize: 14,
        fontWeight: '800',
        marginBottom: 8,
    },
    cardDivider: {
        height: 1,
        backgroundColor: THEME.colors.border,
        marginBottom: 8,
    },
    cardDesc: {
        color: THEME.colors.white,
        fontSize: 13,
    },

    detailContainer: {
        flex: 1,
        backgroundColor: THEME.colors.background,
    },
    topBar: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: THEME.spacing.paddingStandard,
        paddingVertical: 12,
        borderBottomWidth: THEME.borderWidth.default,
        borderBottomColor: THEME.colors.primary,
        backgroundColor: THEME.colors.background,
    },
    actionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    topBarText: {
        color: THEME.colors.primary,
        fontSize: 13,
        fontWeight: '800',
    },
    scrollContent: {
        paddingHorizontal: THEME.spacing.paddingStandard,
        paddingVertical: 16,
        gap: 16,
    },
    mainCard: {
        backgroundColor: THEME.colors.container,
        borderTopWidth: THEME.borderWidth.default,
        borderLeftWidth: THEME.borderWidth.default,
        borderRightWidth: 0,
        borderBottomWidth: 0,
        borderColor: THEME.colors.border,
        borderRadius: THEME.borderRadius.default,
        padding: THEME.spacing.paddingArticleContainer,
        gap: 12,
    },
    cardSection: {
        backgroundColor: THEME.colors.container,
        borderTopWidth: THEME.borderWidth.default,
        borderLeftWidth: THEME.borderWidth.default,
        borderRightWidth: 0,
        borderBottomWidth: 0,
        borderColor: THEME.colors.border,
        borderRadius: THEME.borderRadius.default,
        padding: THEME.spacing.paddingArticleContainer,
        gap: 12,
    },
    tagRow: {
        flexDirection: 'row',
        gap: 8,
        flexWrap: 'wrap',
    },
    mainTitle: {
        color: THEME.colors.white,
        fontSize: 22,
        fontWeight: '800',
        lineHeight: 28,
    },
    detailImage: {
        width: '100%',
        height: 180,
        borderRadius: THEME.borderRadius.default,
        borderBottomWidth: THEME.borderWidth.default,
        borderRightWidth: THEME.borderWidth.default,
        borderColor: THEME.colors.border,
        marginVertical: 4,
    },
    leadText: {
        color: THEME.colors.contrast,
        fontSize: 14,
        lineHeight: 20,
    },
    sectionTitle: {
        color: THEME.colors.primary,
        fontSize: 18,
        fontWeight: '800',
    },
    sectionDivider: {
        height: THEME.borderWidth.default,
        backgroundColor: THEME.colors.primary,
        marginBottom: 4,
    },

    progressHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 4,
    },
    progressHeaderText: {
        color: THEME.colors.primary,
        fontSize: 12,
        fontWeight: '800',
    },
    progressTrack: {
        height: 6,
        backgroundColor: THEME.colors.background,
        borderRadius: THEME.borderRadius.rounded,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: THEME.colors.border,
    },
    progressFill: {
        height: '100%',
        backgroundColor: THEME.colors.primary,
        borderRadius: THEME.borderRadius.rounded,
    },

    stepCard: {
        backgroundColor: THEME.colors.background,
        borderBottomWidth: THEME.borderWidth.default,
        borderRightWidth: THEME.borderWidth.default,
        borderColor: THEME.colors.border,
        borderRadius: THEME.borderRadius.default,
        padding: 12,
    },
    stepText: {
        color: THEME.colors.contrast,
        fontSize: 13,
        lineHeight: 18,
    },

    nextButton: {
        backgroundColor: THEME.colors.primary,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: THEME.spacing.buttonHorizontal,
        paddingVertical: THEME.spacing.buttonVertical,
        borderRadius: THEME.borderRadius.default,
        marginTop: 4,
        flex: 1,
    },
    nextButtonText: {
        color: THEME.colors.black,
        fontSize: 13,
        fontWeight: '800',
    },
    buttonsRow: {
        display: 'flex',
        flexDirection: 'row',
        gap: THEME.spacing.gap,
        width: 'auto',
    }
});